display_name: Magic
package_name: Magic
maintainer:
  name: appshub
  email: appshubcc@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - Magic
  - Clash
  - ClashMeta
  - Mihomo
  - Proxy

generic_name: Magic

categories:
  - Network

startup_notify: true

postinstall_scripts:
  - |
    CORE_PATH="/usr/share/Magic/MagicCore"
    if [ -f "$CORE_PATH" ]; then
      chown root:root "$CORE_PATH" 2>/dev/null || true
      chmod +sx "$CORE_PATH" 2>/dev/null || true
    fi
postuninstall_scripts:
  - |
    CORE_PATH="/usr/share/Magic/MagicCore"
    if [ -f "$CORE_PATH" ]; then
      chmod -s "$CORE_PATH" 2>/dev/null || true
    fi